--- # ERROR HANDLING EXAMPLE    
- hosts: apacheweb
  user: test
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Execute a command that will fail
      command: /bin/false
      ignore_errors: yes
    - yum: pkg=telnet state=latest
