--- # My first YAML Playbook for Ansible
- hosts: apacheweb
  user: test
  become: yes
  connection: ssh
  gather_facts: no
  vars:
    playbook_version: 0.1b
  vars_files:
   - /home/test/Playbooks/conf/copyright.yml
   - /home/test/Playbooks/conf/webdefaults.yml
  tasks:
    - name: Install Apache Web Server
      action: yum name=httpd state=installed
      async:  300
      poll: 3
      notify: RestartHTTPD
  handlers:
    - name: RestartHTTPD
      action: service name=httpd state=restarted
